### PR TITLE
(#325) Bump parent

### PR DESCRIPTION
**Pull request by andreoss**
- Bump parent 
- Should fix issues caused by Lombok on JDK 11

https://github.com/rzwitserloot/lombok/issues/1572

### CODE REVIEW

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by andreoss** [comment]
@yegor256 Please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss merged, thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi#326` is not assigned, can't get performer

**Pull request merged**
