### PR TITLE
Update parent

### PR DESCRIPTION
**Pull request by andreoss**
- Bump `jcabi-parent`

### CODE REVIEW

**Comment by andreoss** [comment]
@rultor try merge?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/jcabi/jcabi/issues/324#issuecomment-657341695); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `1.25.2`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi#324` is not assigned, can't get performer

**Comment by yegor256** [comment]
@andreoss thanks!

**Pull request merged**
