### PR TITLE
Upgrade to com.jcabi.parent 0.34

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by cvrebert** [comment]
@yegor256 Please, tag a release.

**Comment by yegor256** [comment]
@rultor release, tag is `1.19`

**Comment by cvrebert** [comment]
@yegor256 Thanks, last follow-up: https://github.com/jcabi/jcabi-github/pull/1138

**Pull request merged**
